[package]
name = "zed_neptune_theme"
version = "0.1.0"
authors = ["Rhelvetican <bionicvnb@gmail.com>"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = {version = "1", features = ["preserve_order"] }
